version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}gamesmarket
    build:
      context: .
      dockerfile: Gamesmarket/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=MySuperPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  client:
    image: client
    build:
      context: ./Gamesmarket.ReactWeb
      dockerfile: Dockerfile
    ports:
      - "5001:3000"

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - backend

volumes:
  sqlvolume:
